### ISSUE TITLE
Unauthorized error - idk why heres the error below 

### ISSUE THREAD

**Issue by UnPurgable** [ke9dgu8t9jq/Rape-Selfbot#3]
[ I just copied value from science area in discord for my token idk what i did wrong ]

Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\discord\http.py", line 300, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Python39\lib\site-packages\discord\http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Dung\Desktop\Rape-Selfbot-main\rape.py", line 1831, in <module>
    bot.run(token)
  File "C:\Python39\lib\site-packages\discord\client.py", line 723, in run
    return future.result()
  File "C:\Python39\lib\site-packages\discord\client.py", line 702, in runner
    await self.start(*args, **kwargs)
  File "C:\Python39\lib\site-packages\discord\client.py", line 665, in start
    await self.login(*args, bot=bot)
  File "C:\Python39\lib\site-packages\discord\client.py", line 511, in login
    await self.http.static_login(token.strip(), bot=bot)
  File "C:\Python39\lib\site-packages\discord\http.py", line 304, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000019FF710A8B0>
Traceback (most recent call last):
  File "C:\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000019FF710A8B0>
Traceback (most recent call last):
  File "C:\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Python39\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed

**Comment by ke9dgu8t9jq** [comment]
this is a common issue, RapeV2 utilizes discord.py-self. Meaning it is a different type of discord library
how to fix?
make sure you're using python 3.10 and uninstall discord AND discord.py
then install discord, and discord.py-self NOT discord.py, but discord.py-self. after all this is done delete config.json and rerun the selfbot and youll be all set.

**Comment by ke9dgu8t9jq** [comment]
> [ I just copied value from science area in discord for my token idk what i did wrong ]
> 
> Traceback (most recent call last): File "C:\Python39\lib\site-packages\discord\http.py", line 300, in static_login data = await self.request(Route('GET', '/users/@me')) File "C:\Python39\lib\site-packages\discord\http.py", line 254, in request raise HTTPException(r, data) discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "C:\Users\Dung\Desktop\Rape-Selfbot-main\rape.py", line 1831, in bot.run(token) File "C:\Python39\lib\site-packages\discord\client.py", line 723, in run return future.result() File "C:\Python39\lib\site-packages\discord\client.py", line 702, in runner await self.start(*args, **kwargs) File "C:\Python39\lib\site-packages\discord\client.py", line 665, in start await self.login(*args, bot=bot) File "C:\Python39\lib\site-packages\discord\client.py", line 511, in login await self.http.static_login(token.strip(), bot=bot) File "C:\Python39\lib\site-packages\discord\http.py", line 304, in static_login raise LoginFailure('Improper token has been passed.') from exc discord.errors.LoginFailure: Improper token has been passed. Exception ignored in: <function _ProactorBasePipeTransport.**del** at 0x0000019FF710A8B0> Traceback (most recent call last): File "C:\Python39\lib\asyncio\proactor_events.py", line 116, in **del** self.close() File "C:\Python39\lib\asyncio\proactor_events.py", line 108, in close self._loop.call_soon(self._call_connection_lost, None) File "C:\Python39\lib\asyncio\base_events.py", line 746, in call_soon self._check_closed() File "C:\Python39\lib\asyncio\base_events.py", line 510, in _check_closed raise RuntimeError('Event loop is closed') RuntimeError: Event loop is closed Exception ignored in: <function _ProactorBasePipeTransport.**del** at 0x0000019FF710A8B0> Traceback (most recent call last): File "C:\Python39\lib\asyncio\proactor_events.py", line 116, in **del** File "C:\Python39\lib\asyncio\proactor_events.py", line 108, in close File "C:\Python39\lib\asyncio\base_events.py", line 746, in call_soon File "C:\Python39\lib\asyncio\base_events.py", line 510, in _check_closed RuntimeError: Event loop is closed
